export const sentenceList = [
  { cn: "每天进步一点点", en: "Progress a little bit every day" },
  { cn: "坚持就是胜利", en: "Perseverance leads to victory" },
  { cn: "你比昨天更优秀", en: "You are better than yesterday" },
  { cn: "保持热爱，奔赴山海", en: "Keep loving and keep going" },
  { cn: "相信自己，你可以的", en: "Believe in yourself, you can do it" },
  { cn: "越努力，越幸运", en: "The harder you work, the luckier you get" },
  { cn: "学习永不太晚", en: "It is never too late to learn" },
  { cn: "今天的努力，明天的实力", en: "Today's effort is tomorrow's strength" },
  { cn: "不要放弃，你很棒", en: "Don't give up, you are amazing" },
  { cn: "自律给我自由", en: "Self-discipline gives me freedom" },
  { cn: "行动是治愈恐惧的良药", en: "Action is the antidote to fear" },
  { cn: "梦想不大，开始就好", en: "The dream is not big, just start" },
  { cn: "每一次努力，都不会白费", en: "Every effort will not be wasted" },
  { cn: "慢慢来，比较快", en: "Slow down, you will go faster" },
  { cn: "生活明朗，万物可爱", en: "Life is bright, everything is lovely" },
  { cn: "未来可期，人间值得", en: "The future is promising, the world is worthy" },
  { cn: "做自己的太阳，无需借谁的光", en: "Be your own sun, no need to borrow light" },
  { cn: "默默努力，悄悄拔尖", en: "Work hard quietly, excel quietly" },
  { cn: "心有光芒，必有远方", en: "With light in heart, there is a distant future" },
  { cn: "平凡的脚步，也能走完伟大的行程", en: "Ordinary steps can finish a great journey" },
  { cn: "你只管努力，剩下的交给时间", en: "Just work hard, leave the rest to time" },
  { cn: "生活原本沉闷，但跑起来就有风", en: "Life is dull, but there is wind when you run" },
  { cn: "最好的状态是未来可期", en: "The best state is a promising future" },
  { cn: "温柔半两，从容一生", en: "Be gentle, live calmly" },
  { cn: "万事尽心尽力，就很好", en: "Do your best, that's enough" },
  { cn: "愿你眼里的光，不灭", en: "May the light in your eyes never fade" },
  { cn: "知足且上进，温柔且坚定", en: "Be content and progressive, gentle and firm" },
  { cn: "不负自己，不负岁月", en: "Live up to yourself and the years" },
  { cn: "以梦为马，不负韶华", en: "Take dreams as horses, live up to youth" },
  { cn: "各自努力，顶峰相见", en: "Work hard separately, meet at the peak" },
  { cn: "星光不问赶路人，时光不负有心人", en: "Time waits for no one, but rewards those who strive" },
  { cn: "前路浩浩荡荡，万事尽可期待", en: "The road ahead is vast, everything is expected" },
  { cn: "熬过无人问津的日子，才能拥抱诗和远方", en: "Endure the lonely days to embrace poetry and distance" },
  { cn: "与其仰望星空，不如脚踏实地", en: "Better to walk steadily than to stare at stars" },
  { cn: "所有光芒，都需要时间才能被看到", en: "All brilliance takes time to be seen" },
  { cn: "你若盛开，蝴蝶自来", en: "If you bloom, butterflies will come" },
  { cn: "心若向阳，无畏悲伤", en: "If the heart faces the sun, there is no fear of sorrow" },
  { cn: "不辜负每一份热情，不讨好每一份冷漠", en: "Live up to enthusiasm, not coldness" },
  { cn: "慢慢来，谁都有一个发光的过程", en: "Take your time, everyone has a shining process" },
  { cn: "半山腰总是最挤的，你得去山顶看看", en: "The mountainside is crowded, you have to go to the top" },
  { cn: "乾坤未定，你我皆是黑马", en: "The outcome is uncertain, we can all be dark horses" },
  { cn: "纵有疾风起，人生不言弃", en: "Even if the wind rises, never give up in life" },
  { cn: "凡是打不倒你的，终将使你更强大", en: "What doesn't kill you makes you stronger" },
  { cn: "愿你以渺小启程，以伟大结束", en: "May you start small and end great" },
  { cn: "彼方尚有荣光在", en: "There is still glory on the other side" },
  { cn: "没有白走的路，每一步都算数", en: "No step is wasted, every step counts" },
  { cn: "先努力让自己发光，对的人才能迎着光而来", en: "Make yourself shine, then right people come" },
  { cn: "现在的付出，都会是一种沉淀", en: "Current efforts are a kind of accumulation" },
  { cn: "努力只能及格，拼命才会优秀", en: "Hard work only passes, desperate work makes excellence" },
  { cn: "唯有行动，才能解除你所有的不安", en: "Only action can relieve all your uneasiness" },
  { cn: "别在最好的年纪辜负最好的自己", en: "Don't let yourself down at your best age" },
  { cn: "你要悄悄努力，然后惊艳所有人", en: "Work hard quietly and then amaze everyone" },
  { cn: "未来的你，一定会感谢现在拼命的自己", en: "Future you will thank present you" },
  { cn: "所有的出众，都来自于自律和坚持", en: "All excellence comes from self-discipline" },
  { cn: "与其抱怨黑暗，不如提灯前行", en: "Instead of complaining, walk with a light" },
  { cn: "努力到无能为力，拼搏到感动自己", en: "Try until you can't, fight till you're moved" },
  { cn: "心有所期，全力以赴，定有所成", en: "Have expectations, go all out, you will succeed" },
  { cn: "不逼自己一把，永远不知道自己多优秀", en: "You never know how good you are until you try" },
  { cn: "你可以平凡，但不能平庸", en: "You can be ordinary, but not mediocre" },
  { cn: "关关难过关关过，前路漫漫亦灿灿", en: "Overcome difficulties one by one, the future is bright" },
  { cn: "凡是过往，皆为序章", en: "What's past is prologue" },
  { cn: "凛冬散尽，星河长明", en: "The cold winter is over, the stars are bright" },
  { cn: "愿你历尽千帆，归来仍是少年", en: "May you remain young after all hardships" },
  { cn: "努力的意义，是让自己有更多选择", en: "The meaning of hard work is to have more choices" },
  { cn: "愿你眼里有光，心中有爱，一路春暖花开", en: "Light in eyes, love in heart, flowers on the road" },
  { cn: "不负光阴，不负自己，不负所爱", en: "Live up to time, yourself and those you love" },
  { cn: "努力是会上瘾的，尤其是尝到甜头之后", en: "Hard work is addictive after tasting rewards" },
  { cn: "生活不会亏待每一个努力向上的人", en: "Life doesn't let hard workers down" },
  { cn: "努力的终点，是活成自己的靠山", en: "The end of effort is being your own support" },
  { cn: "愿你全力以赴，并且满载而归", en: "May you go all out and return fully loaded" },
  { cn: "别让未来的你，讨厌现在的自己", en: "Don't let future you hate present you" },
  { cn: "你有多自律，就有多自由", en: "The more disciplined, the more free" },
  { cn: "每一次发奋努力，必有加倍的赏赐", en: "Every hard effort brings double rewards" },
  { cn: "人生没有等出来的辉煌，只有拼出来的精彩", en: "No glory by waiting, only excellence by fighting" },
  { cn: "愿你历经山河，觉得人间值得", en: "After traveling, you feel life is worthy" },
  { cn: "愿你前程似锦，未来可期", en: "May your future be bright and promising" },
  { cn: "慢慢变好，是给自己最好的礼物", en: "Getting better is the best gift for yourself" },
  { cn: "熬过这段日子，就是万里晴空", en: "Survive this, and everything will be bright" },
  { cn: "努力的人，运气都不会太差", en: "Hard workers are never unlucky" },
  { cn: "愿你乘风破浪，不负韶华时光", en: "May you ride winds and waves, live up to youth" },
  { cn: "心有所向，平凡的日子也会泛着光", en: "With direction, ordinary days shine" },
  { cn: "愿你所得皆所期，所失亦无碍", en: "May you gain what you expect, lose what doesn't matter" },
  { cn: "心有暖阳，何惧风霜", en: "With warm sun in heart, fear no wind or frost" },
  { cn: "所有的惊艳，都来自长久的努力", en: "All amazement comes from long effort" },
  { cn: "愿你一生努力，一生被爱", en: "May you work hard and be loved all life" },
  { cn: "愿你平安喜乐，万事胜意", en: "May you be peaceful, happy, and all go well" },
  { cn: "哪怕万丈深渊，下去也是前程万里", en: "Even a bottomless pit leads to a bright future" },
  { cn: "不必借光而行，你我亦是星辰", en: "You don't need to borrow light, you are also a star" },
  { cn: "追风赶月莫停留，平芜尽处是春山", en: "Chase dreams without stopping, success lies ahead" },
  { cn: "种自己的花，爱自己的宇宙", en: "Grow your own flowers, love your own universe" },
  { cn: "别让怯弱否定了自己，别让懒惰耽误了青春", en: "Don't let timidity deny you, don't let laziness delay youth" },
  { cn: "依然保持热爱，继续奔赴山海", en: "Still keep loving and keep going to the mountains and seas" },
  { cn: "不抱怨，不将就，有自由，有光芒", en: "No complaint, no compromise, be free and bright" },
  { cn: "愿你眼中有光芒，活成你想要的模样", en: "May there be light in your eyes, living as you wish" },
  { cn: "同是风华正茂，怎甘他人之后", en: "We are all young, how can we lag behind others" },
  { cn: "会当凌绝顶，一览众山小", en: "When you stand on top, you'll see all mountains small" },
  { cn: "长风破浪会有时，直挂云帆济沧海", en: "I will set sail and cross the sea" },
  { cn: "愿有前程可奔赴，亦有岁月可回首", en: "May you have a future to go and years to look back" },
  { cn: "不要因为没有掌声而丢掉梦想", en: "Don't give up dreams because of no applause" },
  { cn: "你的努力，终将成就无可替代的自己", en: "Your efforts will make an irreplaceable you" },
  { cn: "把圈子变小，把语言变干净，把努力往上提", en: "Shrink your circle, purify your words, improve efforts" },
  { cn: "现在荒废的每一个瞬间，都是你的未来", en: "Every wasted moment is your future" },
  { cn: "你优秀了，自然有对的人与你并肩", en: "When you are excellent, right people stand by you" },
  { cn: "先变优秀，再想要一切", en: "Become excellent first, then want everything" },
  { cn: "愿你乘风破浪，活成自己喜欢的模样", en: "May you ride waves and be who you want" },
  { cn: "所有的坚持，都是因为热爱", en: "All persistence is because of love" },
  { cn: "努力的意义，是让自己有底气", en: "Hard work gives you confidence and dignity" },
  { cn: "坚持下去，你会看到自己的强大", en: "Keep going; you'll see your own strength" },
  { cn: "愿你披荆斩棘，活成一束光", en: "May you cut through thorns and be a light" },
  { cn: "愿你眼中有星辰，心中有山海", en: "May stars be in your eyes, mountains in your heart" },
  { cn: "努力，是为了遇见更好的自己", en: "Work hard to meet a better you" },
  { cn: "所有的美好，都将如期而至", en: "All good things will come as scheduled" },
  { cn: "不负时光，不负努力，不负守望", en: "Live up to time, effort, and expectation" },
  { cn: "心有山海，静而无边", en: "Heart has mountains, calm and boundless" },
  { cn: "愿你以梦为马，随处可栖", en: "May your dreams be horses, everywhere is home" },
  { cn: "所有的坚持，终会繁花满地", en: "All persistence will finally bloom" },
  { cn: "愿你温柔且坚韧，勇敢又自由", en: "May you be gentle, tough, brave and free" },
  { cn: "生活明朗，未来可期，人生值得", en: "Life is bright, future is promising, worth living" },
  { cn: "愿你全力以赴，不留遗憾", en: "May you go all out without regret" },
  { cn: "努力，是为了更多的选择权", en: "Hard work is for more choices" },
  { cn: "愿你所有努力，终有回报", en: "May all your efforts be rewarded" },
  { cn: "不慌不忙，慢慢发光", en: "Take it easy, shine slowly" },
  { cn: "愿你前程似锦，一路繁花", en: "May your future be bright with flowers" },
  { cn: "所有的坚持，都是为了更好的遇见", en: "All persistence is for better meetings" },
  { cn: "愿你眼里有光，笑里坦荡", en: "Light in your eyes, calm in your smile" },
  { cn: "努力，是为了不辜负自己", en: "Hard work is to live up to yourself" },
  { cn: "愿你乘风破浪，光芒万丈", en: "May you ride waves and shine brightly" },
  { cn: "努力，是为了更好的未来", en: "Hard work is for a better future" },
  { cn: "努力，从来都不晚", en: "It's never too late to work hard" },
  { cn: "愿你历经千帆，依旧热爱生活", en: "After many storms, still love life" },
  { cn: "永远相信美好的事情即将发生", en: "Always believe something wonderful is about to happen" },
  { cn: "少年不惧岁月长，彼方尚有荣光在", en: "Youth fears not the long years, there is glory ahead" },
  { cn: "把每一次跌倒，都当成成长的机会", en: "Take every fall as a chance to grow" },
  { cn: "前路漫漫亦灿灿，往事堪堪亦澜澜", en: "The road is long and bright; past is calm" },
  { cn: "你要优秀到，所有人都不值得你委屈", en: "Be excellent enough to never compromise" },
  { cn: "现在的我，只想安静努力变优秀", en: "Now I just want to work hard quietly" },
  { cn: "努力的人，终将过上与努力匹配的生活", en: "Hard workers get the life they deserve" },
  { cn: "莫愁前路无知己，天下谁人不识君", en: "Don't worry about friends ahead, the world knows you" },
  { cn: "希望你继续兴致盎然地与世界交手", en: "Keep fighting the world with passion" },
  { cn: "且挨过三冬四夏，雪尽后再看梅花", en: "Endure hardships, and you will see beauty after snow" },
  { cn: "今日长缨在手，何时缚住苍龙", en: "Hold the power today, achieve great goals tomorrow" },
  { cn: "且将新火试新茶，诗酒趁年华", en: "Enjoy life and pursue poetry while you are young" },
  { cn: "坚持下去，并非我们坚强，而是别无选择", en: "Keep going not because strong, but no choice" },
  { cn: "哪怕房檐压得再低，也有另一片天空的希望", en: "Even life is hard, there is still hope" },
  { cn: "所有的幸运，都是努力埋下的伏笔", en: "All luck is foreshadowed by hard work" },
  { cn: "提升自己，比仰望别人更有意义", en: "Improving yourself is better than admiring others" },
  { cn: "时光不会怠慢执着而勇敢的人", en: "Time will not neglect persistent and brave people" },
  { cn: "每一天的努力，都是为了靠近梦想", en: "Every day's effort is to get closer to dreams" },
  { cn: "放弃不难，但坚持一定很酷", en: "Giving up is easy, but persistence is cool" },
  { cn: "愿你不负所有，奔赴所有温柔", en: "May you live up to everything and embrace all tenderness" },
  { cn: "前路浩荡，万事皆可期待", en: "The road ahead is vast, everything is expectable" },
  { cn: "忠于自己，热爱生活", en: "Be loyal to yourself and love life" },
  { cn: "心怀希望，所向披靡", en: "With hope, you are invincible" },
  { cn: "万物皆有裂痕，那是光照进来的地方", en: "There are cracks in everything, that's where light comes in" },
  { cn: "黑暗的尽头，一定是光", en: "At the end of darkness, there must be light" },
  { cn: "做一个温柔且有力量的人", en: "Be a gentle and powerful person" },
  { cn: "生活百般滋味，人生需要笑对", en: "Life has many flavors; face it with a smile" },
  { cn: "只要还在路上，就没有到不了的远方", en: "As long as you keep going, you can reach anywhere" },
  { cn: "努力成为自己想成为的那种人", en: "Strive to be the person you want to be" },
  { cn: "不负热爱，无畏山海", en: "Live up to love, fear no mountains and seas" },
  { cn: "心有憧憬，便不惧道阻且长", en: "With vision, fear no long and difficult road" },
  { cn: "每一次坚持，都是成长的勋章", en: "Every persistence is a medal of growth" },
  { cn: "愿你眼中总有光芒，活成想要的模样", en: "May there always be light in your eyes" },
  { cn: "努力向上，成为别人眼中的遥不可及", en: "Work hard to be unattainable in others' eyes" },
  { cn: "所有光芒万丈，皆源于不懈努力", en: "All brilliance comes from unremitting efforts" },
  { cn: "愿你以梦为翼，飞向想去的远方", en: "May you fly to the distance with dreams as wings" },
  { cn: "努力奔跑，只为追上曾经被寄予厚望的自己", en: "Run hard to catch up with yourself" },
  { cn: "生活最好的状态，是心安理得的努力", en: "The best state is to work hard with peace of mind" },
  { cn: "愿你历经风雨，依旧温柔强大", en: "After storms, still gentle and strong" },
  { cn: "每一次蜕变，都藏着不为人知的努力", en: "Every transformation hides unknown efforts" },
  { cn: "保持清醒，努力向上", en: "Stay sober and strive upward" },
  { cn: "愿你所有坚持，都能换来繁花似锦", en: "May all your persistence bring brilliant flowers" },
  { cn: "努力，是为了更好的自己与更远的远方", en: "Work hard for better self and farther distance" },
  { cn: "愿你眼里有星辰，身边有微风，心中有暖阳", en: "Stars in eyes, breeze around, warm sun in heart" },
  { cn: "所有努力，皆有回甘", en: "All efforts have a sweet aftertaste" },
  { cn: "愿你乘风破浪，归来依旧坦荡", en: "Ride waves and return still calm" },
  { cn: "努力的意义，是成为更好的自己", en: "The meaning of hard work is to be better yourself" },
  { cn: "愿你不畏将来，不念过往", en: "May you fear not the future, not miss the past" },
  { cn: "心有丘壑，立马振山河", en: "With vision, you can shake the mountains and rivers" },
  { cn: "愿你眼中有光，行途坦荡", en: "Light in your eyes, smooth road ahead" },
  { cn: "所有汗水，都不会被辜负", en: "All sweat will not be let down" },
  { cn: "愿你以渺小启程，伟大结束", en: "Start small and end great" },
  { cn: "努力，让平凡的日子闪闪发光", en: "Make ordinary days shine with hard work" },
  { cn: "愿你不负初心，方得始终", en: "May you keep your original aspiration and succeed" },
  { cn: "生活原本沉闷，但跑起来就有风", en: "Life is dull, but there is wind when you run" },
  { cn: "愿你永远年轻，永远热泪盈眶", en: "May you always be young and passionate" },
  { cn: "所有美好，都在奔你而来", en: "All good things are coming to you" },
  { cn: "愿你温柔坚定，光芒万丈", en: "May you be gentle, firm and brilliant" },
  { cn: "努力，是人生最亮的底色", en: "Hard work is the brightest background of life" },
  { cn: "愿你一路向前，永不回头", en: "May you move forward and never look back" },
  { cn: "心有热爱，可抵岁月漫长", en: "With love, resist the long years" },
  { cn: "愿你所有等待，都不被辜负", en: "May all your waiting be rewarded" },
  { cn: "努力，是为了不辜负此生", en: "Work hard to live up to this life" },
  { cn: "愿你平安顺遂，万事无忧", en: "May you be safe, smooth and worry-free" },
  { cn: "心有方向，何惧路长", en: "With direction, fear no long road" },
  { cn: "所有坚持，终有回响", en: "All persistence will eventually echo" },
  { cn: "愿你历经世事，依旧纯粹明朗", en: "After experiences, still pure and bright" },
  { cn: "努力，让梦想照进现实", en: "Make dreams come true with hard work" },
  { cn: "愿你前程万里，一生无忧", en: "May you have a bright future and no worries" },
  { cn: "心有勇气，万事可期", en: "With courage, everything is expectable" },
  { cn: "所有付出，终有回报", en: "All efforts will be rewarded" },
  { cn: "愿你一生清澈明朗，做自己想做的人", en: "May you be clear and be who you want" },
  { cn: "努力向上，向阳生长", en: "Strive upward and grow toward the sun" },
  { cn: "愿你乘风破浪，所向披靡", en: "Ride waves and be invincible" },
  { cn: "心有梦想，何惧路远", en: "With dreams, fear no long road" },
  { cn: "所有努力，都在悄悄开花", en: "All efforts are quietly blooming" },
  { cn: "愿你眼里有光，心中有梦，脚下有路", en: "Light in eyes, dreams in heart, road under feet" },
  { cn: "努力，是为了更好的明天", en: "Work hard for a better tomorrow" },
  { cn: "愿你不负时光，努力向前", en: "Live up to time and move forward" },
  { cn: "心有温暖，无畏寒凉", en: "With warmth, fear no cold" },
  { cn: "所有拼搏，终会结果", en: "All struggles will bear fruit" },
  { cn: "愿你一生努力，一生被温柔以待", en: "Work hard and be treated gently all life" },
  { cn: "努力，让自己无可替代", en: "Make yourself irreplaceable with hard work" },
  { cn: "愿你前程似锦，一生幸福", en: "May you have a bright future and a happy life" },
  { cn: "心有信念，万事皆成", en: "With faith, everything will succeed" },
  { cn: "所有奋斗，都有意义", en: "All struggles are meaningful" },
  { cn: "愿你历经沧桑，依旧热爱生活", en: "After vicissitudes, still love life" },
  { cn: "努力，是最美的姿态", en: "Hard work is the most beautiful gesture" },
  { cn: "愿你一路繁花，前程灿烂", en: "Flowers all the way, bright future" },
  { cn: "心有理想，风雨兼程", en: "With ideals, go through all storms" },
  { cn: "所有坚持，都是值得的", en: "All persistence is worthwhile" },
  { cn: "愿你眼里有光，不惧风霜", en: "Light in eyes, fear no wind and frost" },
  { cn: "努力，是为了心中的热爱", en: "Work hard for the love in heart" },
  { cn: "愿你一生顺遂，平安喜乐", en: "May you be smooth, safe and happy all life" },
  { cn: "心有热爱，奔赴远方", en: "With love, go to the distance" },
  { cn: "所有汗水，都将闪耀", en: "All sweat will shine" },
  { cn: "愿你不负韶华，未来可期", en: "Live up to youth, future is promising" },
  { cn: "努力，让生活充满希望", en: "Make life full of hope with hard work" },
  { cn: "愿你一路向阳，温暖如初", en: "Face the sun and stay warm as before" },
  { cn: "心有光芒，无畏黑暗", en: "With light, fear no darkness" },
  { cn: "所有努力，终将闪耀", en: "All efforts will eventually shine" },
  { cn: "愿你一生被爱，勇敢自由", en: "Be loved, brave and free all life" },
  { cn: "努力，是为了更好的生活", en: "Work hard for a better life" },
  { cn: "愿你前程光明，一生欢喜", en: "Bright future, joy all life" },
  { cn: "心有希望，万事顺利", en: "With hope, everything goes well" },
  { cn: "所有奋斗，终将辉煌", en: "All struggles will eventually be brilliant" },
  { cn: "愿你历经风雨，依旧阳光", en: "After storms, still sunny" },
  { cn: "努力，是成功的基石", en: "Hard work is the cornerstone of success" },
  { cn: "愿你一路顺风，万事称心", en: "Smooth journey, everything satisfactory" },
  { cn: "心有追求，永不言弃", en: "With pursuit, never give up" },
  { cn: "所有努力，铸就辉煌", en: "All efforts make brilliance" },
  { cn: "愿你一生平安，幸福美满", en: "Safe and happy all life" },
  { cn: "心有阳光，处处温暖", en: "With sunshine, everywhere is warm" },
  { cn: "努力，让梦想成真", en: "Make dreams come true with hard work" },
  { cn: "愿你前程远大，光芒四射", en: "Great future, brilliant shine" },
  { cn: "心有力量，无惧挑战", en: "With strength, fear no challenges" },
  { cn: "所有拼搏，铸就成功", en: "All struggles make success" },
  { cn: "愿你一生快乐，无忧无虑", en: "Happy and carefree all life" },
  { cn: "心有热爱，永不褪色", en: "With love, never fade" },
  { cn: "努力，是最美的风景", en: "Hard work is the most beautiful scenery" },
  { cn: "愿你一路辉煌，万事胜意", en: "Brilliant all the way, everything wins" },
  { cn: "心有方向，勇往直前", en: "With direction, march forward courageously" },
  { cn: "所有坚持，成就梦想", en: "All persistence achieves dreams" },
  { cn: "愿你一生安康，喜乐常伴", en: "Healthy and joyful all life" },
  { cn: "心有美好，所见皆甜", en: "With beauty, everything is sweet" },
  { cn: "努力，让人生更精彩", en: "Make life more wonderful with hard work" },
  { cn: "愿你前程无忧，光芒万丈", en: "No worries, brilliant future" },
  { cn: "心有勇气，直面风雨", en: "With courage, face storms directly" },
  { cn: "所有付出，铸就幸福", en: "All efforts make happiness" },
  { cn: "愿你一生顺遂，心想事成", en: "Smooth life, all wishes come true" },
  { cn: "心有梦想，未来可期", en: "With dreams, future is promising" },
  { cn: "努力，是人生的信仰", en: "Hard work is the belief of life" },
  { cn: "愿你一路高歌，前程似锦", en: "Sing all the way, bright future" },
  { cn: "心有坚定，万事可成", en: "With firmness, everything can be achieved" },
  { cn: "所有奋斗，皆有收获", en: "All struggles have gains" },
  { cn: "愿你一生温暖，纯良不舍", en: "Warm and kind all life" },
  { cn: "心有诗意，人间值得", en: "With poetry, the world is worthy" },
  { cn: "努力，让生活更美好", en: "Make life better with hard work" },
  { cn: "愿你前程璀璨，一生辉煌", en: "Bright future, brilliant life" },
  { cn: "心有执着，终获成功", en: "With persistence, eventually succeed" },
  { cn: "所有努力，皆为成长", en: "All efforts are for growth" },
  { cn: "愿你一生幸福，万事圆满", en: "Happy life, everything perfect" },
  { cn: "心有善意，一路芬芳", en: "With kindness, fragrance all the way" },
  { cn: "努力，是对自己最好的馈赠", en: "Hard work is the best gift for yourself" },
  { cn: "愿你一路坦途，万事顺意", en: "Smooth road, everything goes well" },
  { cn: "心有憧憬，未来无限", en: "With vision, infinite future" },
  { cn: "所有拼搏，皆为荣耀", en: "All struggles are for glory" },
  { cn: "愿你一生安好，喜乐平安", en: "Safe and joyful all life" },
  { cn: "心有美好，岁月温柔", en: "With beauty, years are gentle" },
  { cn: "努力，让未来充满可能", en: "Make future full of possibilities with hard work" },
  { cn: "愿你前程光明，一路繁花", en: "Bright future, flowers all the way" },
  { cn: "心有坚毅，无惧艰难", en: "With perseverance, fear no hardships" },
  { cn: "所有坚持，皆为荣光", en: "All persistence is for glory" },
  { cn: "愿你一生如意，岁岁安康", en: "All the best, safe every year" },
  { cn: "心有热爱，岁月生香", en: "With love, years produce fragrance" },
  { cn: "努力，是对梦想最好的回应", en: "Hard work is the best response to dreams" },
  { cn: "愿你一路顺风，一生幸福", en: "Smooth journey, happy life" },
  { cn: "心有目标，全力以赴", en: "With goals, go all out" },
  { cn: "所有奋斗，终会圆满", en: "All struggles will eventually be perfect" },
  { cn: "愿你一生平安，万事顺心", en: "Safe life, everything goes well" },
  { cn: "心有阳光，一路芬芳", en: "With sunshine, fragrance all the way" },
  { cn: "努力，让人生充满光芒", en: "Make life full of light with hard work" },
  { cn: "愿你前程似锦，岁岁平安", en: "Bright future, safe every year" },
  { cn: "心有力量，无所不能", en: "With strength, omnipotent" },
  { cn: "所有付出，终得圆满", en: "All efforts will eventually be perfect" },
  { cn: "愿你一生快乐，万事顺遂", en: "Happy life, everything goes well" },
  { cn: "心有梦想，砥砺前行", en: "With dreams, forge ahead" },
  { cn: "努力，是最美的人生态度", en: "Hard work is the best attitude towards life" },
  { cn: "愿你一路辉煌，岁岁欢喜", en: "Brilliant all the way, joy every year" },
  { cn: "心有信念，勇往直前", en: "With faith, march forward courageously" },
  { cn: "所有坚持，终成正果", en: "All persistence achieves final success" },
  { cn: "愿你一生安康，万事胜意", en: "Healthy life, everything wins" },
  { cn: "心有美好，勇往直前", en: "With beauty, march forward courageously" },
  { cn: "努力，让每一天都充满意义", en: "Make every day meaningful with hard work" },
  { cn: "愿你前程万里，一生平安", en: "Bright future, safe life" },
  { cn: "心有勇气，无所畏惧", en: "With courage, fear nothing" },
  { cn: "所有奋斗，终获成功", en: "All struggles eventually succeed" },
  { cn: "愿你一生纯良，不舍爱与自由", en: "Kind life, never give up love and freedom" },
  { cn: "心有诗意，不畏将来", en: "With poetry, fear not the future" },
  { cn: "努力，是通往成功的唯一路径", en: "Hard work is the only path to success" },
  { cn: "愿你一路繁花，一生幸福", en: "Flowers all the way, happy life" },
  { cn: "心有坚定，无惧风浪", en: "With firmness, fear no storms" },
  { cn: "所有努力，终会绽放", en: "All efforts will eventually bloom" },
  { cn: "愿你一生顺遂，平安喜乐", en: "Smooth life, safe and joyful" },
  { cn: "心有热爱，勇往直前", en: "With love, march forward courageously" },
  { cn: "努力，让生命更加璀璨", en: "Make life more brilliant with hard work" },
  { cn: "愿你前程光明，岁岁欢喜", en: "Bright future, joy every year" },
  { cn: "心有希望，砥砺前行", en: "With hope, forge ahead" },
  { cn: "所有拼搏，终得回报", en: "All struggles will be rewarded" },
  { cn: "愿你一生安好，万事顺心", en: "Safe life, everything goes well" },
  { cn: "心有温暖，勇往直前", en: "With warmth, march forward courageously" },
  { cn: "努力，是对人生最好的交代", en: "Hard work is the best explanation for life" },
  { cn: "愿你一路坦途，一生辉煌", en: "Smooth road, brilliant life" },
  { cn: "心有目标，砥砺前行", en: "With goals, forge ahead" },
  { cn: "所有坚持，皆有收获", en: "All persistence has gains" },
  { cn: "愿你一生幸福，平安顺遂", en: "Happy life, safe and smooth" },
  { cn: "心有光芒，一路向前", en: "With light, move forward all the way" },
  { cn: "努力，让梦想不再遥远", en: "Make dreams not far away with hard work" },
  { cn: "愿你前程似锦，一生安康", en: "Bright future, healthy life" },
  { cn: "心有坚毅，勇往直前", en: "With perseverance, march forward courageously" },
  { cn: "所有付出，皆有回响", en: "All efforts have echoes" },
  { cn: "愿你一生快乐，平安健康", en: "Happy life, safe and healthy" },
  { cn: "心有梦想，永不放弃", en: "With dreams, never give up" },
  { cn: "努力，让人生更加辉煌", en: "Make life more brilliant with hard work" },
  { cn: "愿你一路顺风，万事圆满", en: "Smooth journey, everything perfect" },
  { cn: "心有信念，无所畏惧", en: "With faith, fear nothing" },
  { cn: "所有奋斗，皆成荣耀", en: "All struggles become glory" },
  { cn: "愿你一生顺遂，喜乐安康", en: "Smooth life, joyful and healthy" },
  { cn: "心有阳光，勇往直前", en: "With sunshine, march forward courageously" },
  { cn: "努力，是最美的追梦姿态", en: "Hard work is the most beautiful gesture of chasing dreams" },
  { cn: "愿你前程璀璨，一生平安", en: "Bright future, safe life" },
  { cn: "心有力量，砥砺前行", en: "With strength, forge ahead" },
  { cn: "所有坚持，终获荣光", en: "All persistence eventually gains glory" },
  { cn: "愿你一生安好，幸福美满", en: "Safe life, happy and perfect" },
  { cn: "心有美好，岁月生香", en: "With beauty, years produce fragrance" },
  { cn: "努力，让每一天都闪闪发光", en: "Make every day shine with hard work" },
  { cn: "愿你一路繁花，前程万里", en: "Flowers all the way, bright future" },
  { cn: "心有执着，勇往直前", en: "With persistence, march forward courageously" },
  { cn: "所有拼搏，终成正果", en: "All struggles achieve final success" },
  { cn: "愿你一生平安，喜乐常伴", en: "Safe life, joy always" },
  { cn: "心有热爱，岁月温柔", en: "With love, years are gentle" },
  { cn: "努力，是成功的必经之路", en: "Hard work is the only way to success" },
  { cn: "愿你前程光明，一生顺遂", en: "Bright future, smooth life" },
  { cn: "心有坚毅，无所不能", en: "With perseverance, omnipotent" },
  { cn: "所有努力，皆为荣耀", en: "All efforts are for glory" },
  { cn: "愿你一生快乐，万事圆满", en: "Happy life, everything perfect" },
  { cn: "心有梦想，一路向前", en: "With dreams, move forward all the way" },
  { cn: "努力，让生命绽放光彩", en: "Make life shine with hard work" },
  { cn: "愿你一路辉煌，平安顺遂", en: "Brilliant all the way, safe and smooth" },
  { cn: "心有信念，砥砺前行", en: "With faith, forge ahead" },
  { cn: "所有奋斗，终有回报", en: "All struggles will be rewarded" },
  { cn: "愿你一生安康，喜乐平安", en: "Healthy life, joyful and safe" },
  { cn: "心有阳光，岁月温暖", en: "With sunshine, years are warm" },
  { cn: "努力，是对未来最好的铺垫", en: "Hard work is the best bedding for future" },
  { cn: "愿你前程似锦，万事顺意", en: "Bright future, everything goes well" },
  { cn: "心有勇气，砥砺前行", en: "With courage, forge ahead" },
  { cn: "所有付出，终成辉煌", en: "All efforts eventually become brilliant" },
  { cn: "愿你一生纯良，平安喜乐", en: "Kind life, safe and joyful" },
  { cn: "心有诗意，一路芬芳", en: "With poetry, fragrance all the way" },
  { cn: "努力，让人生充满希望", en: "Make life full of hope with hard work" },
  { cn: "愿你一路坦途，岁岁安康", en: "Smooth road, healthy every year" },
  { cn: "心有坚定，无所畏惧", en: "With firmness, fear nothing" },
  { cn: "所有坚持，皆为成功", en: "All persistence is for success" },
  { cn: "愿你一生幸福，万事胜意", en: "Happy life, everything wins" },
  { cn: "心有美好，勇往直前", en: "With beauty, march forward courageously" },
  { cn: "努力，是最美的人生风景", en: "Hard work is the most beautiful scenery of life" },
  { cn: "愿你前程万里，喜乐安康", en: "Bright future, joyful and healthy" },
  { cn: "心有目标，勇往直前", en: "With goals, march forward courageously" },
  { cn: "所有拼搏，皆有收获", en: "All struggles have gains" },
  { cn: "愿你一生安好，岁岁平安", en: "Safe life, safe every year" },
  { cn: "心有光芒，岁月静好", en: "With light, years are quiet" },
  { cn: "努力，让梦想照进人生", en: "Make dreams shine into life with hard work" },
  { cn: "愿你一路繁花，一生顺遂", en: "Flowers all the way, smooth life" },
  { cn: "心有力量，勇往直前", en: "With strength, march forward courageously" },
  { cn: "所有奋斗，终成圆满", en: "All struggles eventually become perfect" },
  { cn: "愿你一生快乐，平安顺遂", en: "Happy life, safe and smooth" },
  { cn: "心有热爱，一路向前", en: "With love, move forward all the way" },
  { cn: "努力，是对自己最好的负责", en: "Hard work is the best responsibility for yourself" },
  { cn: "愿你前程光明，万事圆满", en: "Bright future, everything perfect" },
  { cn: "心有希望，无所畏惧", en: "With hope, fear nothing" },
  { cn: "所有努力，终成大器", en: "All efforts eventually become great" },
  { cn: "愿你一生安康，万事顺心", en: "Healthy life, everything goes well" },
  { cn: "心有温暖，岁月芬芳", en: "With warmth, years are fragrant" },
  { cn: "努力，让人生更加精彩", en: "Make life more wonderful with hard work" },
  { cn: "愿你一路辉煌，岁岁平安", en: "Brilliant all the way, safe every year" },
  { cn: "心有坚毅，一路向前", en: "With perseverance, move forward all the way" },
  { cn: "所有付出，皆获成功", en: "All efforts achieve success" },
  { cn: "愿你一生平安，万事顺遂", en: "Safe life, everything goes well" },
  { cn: "心有梦想，无所畏惧", en: "With dreams, fear nothing" },
  { cn: "努力，是最美的奋斗姿态", en: "Hard work is the most beautiful struggle gesture" },
  { cn: "愿你前程似锦，一生快乐", en: "Bright future, happy life" },
  { cn: "心有信念，一路向前", en: "With faith, move forward all the way" },
  { cn: "所有坚持，终获成功", en: "All persistence eventually achieves success" }
];